Resource view
archivesspace/e2e-tests pull request #40
Opened 2024-11-29 10:17 UTC by kdimopulu

2024-12-19 14:34 UTC, brianzelip requested changes
@kdimopulu looks good. Again below is a comment about adding constraints to an expectation.

2024-12-19 14:34 UTC, brianzelip commented on staff_features/resources/step_definitions/resource_shared.rb
> +  expect(find('h2').text).to eq "Resource #{@uuid} Resource"
I think adding another constraint here is better than just a heading (I know the existing tests often look for only a heading), maybe expecting `'.record-toolbar button', text: Edit`, or expecting the exact URL, etc.

2024-12-19 15:07 UTC, brianzelip commented on staff_features/resources/step_definitions/resource_shared.rb
> +  expect(find('h2').text).to eq "Resource #{@uuid} Resource"
Walking this suggestion back based on https://github.com/archivesspace/e2e-tests/pull/41#discussion_r1892359072

2024-12-20 21:23 UTC, balmas commented on staff_features/resources/step_definitions/resource_view.rb
> +  expect(search_result_rows[1]).to have_text @accession_a_uuid
should accession_a_uuid be before accession_b_uid if sorted by ascending identifier?

2024-12-28 18:50 UTC, merged