Digital Object view
archivesspace/e2e-tests pull request #54
Opened 2024-12-18 08:33 UTC by kdimopulu

2024-12-19 11:43 UTC, brianzelip approved these changes
👍🏼

2024-12-19 11:50 UTC, brianzelip requested changes
See failing test, https://github.com/archivesspace/e2e-tests/actions/runs/12392164627/job/34590746478?pr=54

2025-01-03 11:53 UTC, blacksmith-welder commented
> See failing test, https://github.com/archivesspace/e2e-tests/actions/runs/12392164627/job/34590746478?pr=54

@brianzelip 
This failing test is irrelevant to this PR. I have already provided a fix for this one on another PR.
Do you think we are good to merge?

2025-01-31 20:46 UTC, donaldjosephsmith approved these changes

2025-02-05 16:39 UTC, merged